### ISSUE TITLE
Expose a query an interface to handle reconnections on error

### ISSUE THREAD

**Issue by mattetti** [eaigner/jet#10]
Due to a bug in Go https://code.google.com/p/go/issues/detail?id=5718 autoreconnection doesn't work with prepared statements. It sometimes leads to issues and bad connections. I would be nice if Jet could expose an interface to handle errors and let the developers reconnect and retry the query.

I noticed this method, but it's not currently exported so I can't hook into it.
https://github.com/eaigner/jet/blob/master/query.go#L132

Thanks

**Comment by eaigner** [comment]
If I'm not mistaken, you can avoid this issue by just not setting an LRU cache on the jet Db object for now. Since last revision, the LRU is only used (and prepared statements cached) when it is explicitly set on the instance.

**Comment by mattetti** [comment]
Ahh great, if you just help me out with the time parsing issue I can update
to the latest version and not use the prepared statements for now.

**Comment by eaigner** [comment]
The new LRU implementation should discard prepared statements on error automatically. Not sure if the automatic reconnection should be jet's concern.

Sounds more like a `database/sql` and driver related issue.

Closing for now, please reopen if needed.
