### ISSUE TITLE
the newQueryId in utils.go are not thread safe

### ISSUE THREAD

**Issue by slene** [eaigner/jet#11]
becaues the `gen.Intn` are not thread safe

```
package main

import (
    "math/rand"
    "runtime"
    "sync"
    "time"
)
var (
    gen = rand.New(rand.NewSource(time.Now().UnixNano()))
)

func main() {
    runtime.GOMAXPROCS(2)
    g := sync.WaitGroup{}
    for i := 0; i < 2; i++ {
        g.Add(1)
        go func() {
            _ = gen.Int()
            g.Done()
        }()
    }
    g.Wait()
}
```
# 

WARNING: DATA RACE
Write by goroutine 5:
  math/rand.(_rngSource).Int63()
      /usr/local/go/src/pkg/math/rand/rng.go:233 +0x3a
  math/rand.(_Rand).Int63()
      /usr/local/go/src/pkg/math/rand/rand.go:37 +0x48
  math/rand.(*Rand).Int()
      /usr/local/go/src/pkg/math/rand/rand.go:47 +0x32
  main.func·001()
      /project/works/open/src/example/main.go:45 +0x4f
  gosched0()
      /usr/local/go/src/pkg/runtime/proc.c:1218 +0x9f

Previous write by goroutine 4:
  math/rand.(_rngSource).Int63()
      /usr/local/go/src/pkg/math/rand/rng.go:233 +0x3a
  math/rand.(_Rand).Int63()
      /usr/local/go/src/pkg/math/rand/rand.go:37 +0x48
  math/rand.(*Rand).Int()
      /usr/local/go/src/pkg/math/rand/rand.go:47 +0x32
  main.func·001()
      /project/works/open/src/example/main.go:45 +0x4f
  gosched0()
      /usr/local/go/src/pkg/runtime/proc.c:1218 +0x9f

Goroutine 5 (running) created at:
  main.main()
      /project/works/open/src/example/main.go:47 +0x145
  runtime.main()
      /usr/local/go/src/pkg/runtime/proc.c:182 +0x91

Goroutine 4 (finished) created at:
  main.main()
      /project/works/open/src/example/main.go:47 +0x145
  runtime.main()
      /usr/local/go/src/pkg/runtime/proc.c:182 +0x91
#

**Comment by eaigner** [comment]
Although I run the tests always with `-race` this hasn't popped up yet. I guess wrapping it with a mutex lock would solve this.

**Comment by eaigner** [comment]
Oh... thats because this was already fixed :)

https://github.com/eaigner/jet/blob/master/util.go#L19
