### ISSUE TITLE
Panic in q.stmt.Close() is preventing the "root" error to be passed through

### ISSUE THREAD

**Issue by tcolar** [eaigner/jet#12]
Often if I have a bad SQL query and the mapping failsI don't get the root error, because instead I get a Panic from the q.stmt.close() (query.go:36)

A simple fix was to either prevent the panic q.stmt.close() or this seem to work too:
    if q.db.LRUCache == nil && q.stmt != nil {
      q.stmt.Close()
    }
## Otherwise I would always get a panic like such when Rows() mapping failed:

Running: [go, test] 
warning: building out-of-date packages:
    github.com/eaigner/jet
    github.com/tcolar/phpserializer
installing these packages with 'go test -i' will speed future tests.

2013/09/12 14:10:22 drupsway_test.go:27: Test Start
--- FAIL: TestProducts (0.00 seconds)
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
    panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x28 pc=0x4b883d]

goroutine 4 [running]:
testing.func·004()
    /usr/local/go/src/pkg/testing/testing.go:348 +0xcd
sync/atomic.CompareAndSwapUint32()
    /usr/local/go/src/pkg/sync/atomic/asm_amd64.s:14 +0xd
sync.(_Mutex).Lock(0x28)
    /usr/local/go/src/pkg/sync/mutex.go:43 +0x35
sync.(_RWMutex).Lock(0x28)
    /usr/local/go/src/pkg/sync/rwmutex.go:78 +0x25
database/sql.(_Stmt).Close(0x0, 0x0, 0x0)
    /usr/local/go/src/pkg/database/sql/sql.go:1241 +0x3c
github.com/eaigner/jet.func·001()
    /home/tcolar/DEV/go/src/github.com/eaigner/jet/query.go:36 +0x4c
github.com/eaigner/jet.(_query).Rows(0xc20016bc40, 0x6bf840, 0xc20012a960, 0x0, 0x0, ...)
    /home/tcolar/DEV/go/src/github.com/eaigner/jet/query.go:42 +0xb9

......

goroutine 2 [syscall]:
exit status 2
FAIL 0.034s

---

**Comment by eaigner** [comment]
Fixed in dc32b97335e6050751a0fecf396619b04d0b5020
