### ISSUE TITLE
Struct in structs with joins?

### ISSUE THREAD

**Issue by adam-frisby** [eaigner/jet#14]
In the following example, I would like the User field of the Post struct to be filled in with the user data from the query. Is such a thing possible? Currently, I am running two select statements. First getting the post and then getting the user.

``` go
type User struct {
    Id       int64
    Username string
}

type Post struct {
    Id   int64
    Text string
    User *User
}

func GetPost(id int64) {
    var post Post
    db.Query(`SELECT * FROM "post" LEFT JOIN "user" ON user.id = post.user_id`).Rows(&post)
}
```

**Comment by eaigner** [comment]
Yes, Joins are possible. You just have to use a type that contains all fields you require when deserializing with `Rows(...)`.
