### ISSUE TITLE
issue with new complex value encode/decode interface

### ISSUE THREAD

**Issue by mattetti** [eaigner/jet#15]
Here is my implementation of a MySQL time encoder/decoder: https://gist.github.com/mattetti/6692464

I'm having an issue where I have a User type like this:

``` go
type User struct {
    Id                  int
    Name                string
    Email               string
    CreatedAt           DbTime
}
```

When I save the record, everything works fine, the encoder seems to work. But when I retrieve the row, the decoder reports properly decoding the object (from the output) but the user object itself has a zeroed `CreatedAt` value.

I'm very confused and I'm not sure if that's an issue due to the way I use the interface, or an actual bug.

My test is very simple:

``` go
func TestUserDbTime(t *testing.T) {
  var user User
  u := User{Name: "matt", CreatedAt: DbTime{String:"2013-07-17 06:08:04 +0000 UTC"}}
  u.Create()
    err := Db.Query(`select * from users limit 1`).Rows(&user)
  assert.Nil(t, err)
  t.Logf("user: %#v", user)
  assert.False(t, user.CreatedAt.IsZero())
}

```

Whatever I do, the `user.CreatedAt` value is zeroed. What am I missing?

**Comment by mattetti** [comment]
After digging into the code, I noticed that `setValue` isn't doing what I expect:

``` go
func setValue(from, to reflect.Value) {
    if cto, ok := to.Interface().(ComplexValue); ok {
                fmt.Printf("setting the value of %#v\n", cto)
        cto.Decode(from.Interface())
                fmt.Printf("%#v was decoded\n", cto)
        return
    }
```

```
setting the value of &models.DbTime{String:"", Time:time.Time{sec:0, nsec:0, loc:(*time.Location)(nil)}}
&models.DbTime{String:"", Time:time.Time{sec:0, nsec:0, loc:(*time.Location)(nil)}} was decoded
```

I changed the decode method to hardcode set the String value and it didn't change anything.
It looks like part of the issue is that I'm not using a pointer to my complex value type.
I'll try to look more into it.

**Comment by mattetti** [comment]
So the problem was indeed that `jet` only properly encode/decode structs with pointers to a complex value.

**Comment by eaigner** [comment]
That has nothing to do with Jet itself, that's how structs work.

**Comment by eaigner** [comment]
You should not pass structs by value anyway.

**Comment by eaigner** [comment]
Example http://play.golang.org/p/1gvX3AaQLl

Change `func (x X) Do()` to `func (x *X) Do()` and it will work.

**Comment by mattetti** [comment]
Thanks, I ended up figuring it out, but you might want to show an
example/explain the complex value approach since it's required for people
using MySQL.

**Comment by eaigner** [comment]
There's an example for everything in the unit tests.
