### ISSUE TITLE
Is there no support for floats?

### ISSUE THREAD

**Issue by dnwade** [eaigner/jet#16]
Couldn't successfully query a table containing columns of type decimal. I thought I was doing something wrong, but looking through the tests and source leaves me doubting whether there is support at all.

**Comment by tcolar** [comment]
Don't know if that's helpful to you but i had the same issue, one thing that worked for me is to map them to a string type (go), then i parse that into a float in go (strconv.ParseFloat). Ideally built-in mapping would be better obviously.

**Comment by eaigner** [comment]
First of all, which driver? Second, it's just a matter of adding a float case in [`setValue`](https://github.com/eaigner/jet/blob/master/mapper.go#L116) (and `setValueFromX` funcs), provided that the driver returns a `float` type.

**Comment by eaigner** [comment]
Merged your pull request!
