### ISSUE TITLE
undefined: sha1.Sum

### ISSUE THREAD

**Issue by AndrewVos** [eaigner/jet#21]
➜  ~  go version
go version go1.1.2 linux/amd64

➜  ~  go get github.com/eaigner/jet
# github.com/eaigner/jet

gopath/src/github.com/eaigner/jet/lru.go:84: undefined: sha1.Sum

**Comment by eaigner** [comment]
See http://golang.org/pkg/crypto/sha1/

The current Go version is 1.2.

**Comment by AndrewVos** [comment]
Hah wow. Can't believe I didn't notice that while installing Go and also while creating this issue.

Thanks!
