### ISSUE TITLE
Deadlock when doing a query that returns no data (update)

### ISSUE THREAD

**Issue by tcolar** [eaigner/jet#25]
Since yesterday I've been fighting a serious issue since updating to the latest jet (using go 1.2 amd64).

Symptom is that when I do any kind of "update" query, that query "deadlocks" and never returns.

After much debugging I found the following:
In jet query.Rows() the defer that contains "q.m.Unlock()" was not being called.
Took a while to find why, it turns out another defer, the one for "rows.Close()" is hanging. 

I'm still not getting why rows.Close() is hanging however, i was thinking that maybe it was nil and casing a panic but that doesn't seem to be the case.

If I take out the "defer rows.Close()" then all works properly although I would think that's probably not the right thing to do.

I haven't found yet what might be causing rows.close to hang however .... any ideas ?

**Comment by tcolar** [comment]
Actually also had to add this:
if len(cols) == 0 {
      return nil
}
after "cols, err := rows.Columns()"

It seem without this it also ends up hanging as well

Overall there juts seem to be something going very wrong when there are no rows/columns to be mapped.

For info, my hanging query is simply like such:
    query := `update users set login = ? where uid = ?;`
    err := db.Query(query, u.LoginTs, u.Uid).Run()

**Comment by eaigner** [comment]
Could you provide a test case that for your case?

**Comment by tcolar** [comment]
k, working on it

**Comment by tcolar** [comment]
Attached

On Sat, Jan 4, 2014 at 11:04 AM, Erik Aigner notifications@github.comwrote:

> Could you provide a test case that for your case?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/eaigner/jet/issues/25#issuecomment-31585830
> .
> 
> package drupsway

import (
  "github.com/eaigner/jet"
  _ "github.com/go-sql-driver/mysql"
  "log"
  "testing"
)

var db jet.Db

func init() {
  // Mysql 5.5 Database
  d, err := jet.Open("mysql", "edited:edited@tcp(edited.edited.com:3306)/mydb?charset=utf8")
  if err != nil {
    log.Fatal(err)
  }
  db = *d
  if err = d.Ping(); err != nil {
    log.Fatal("Failed to connect to the database : " + err.Error())
  }
  d.ColumnConverter = jet.SnakeCaseConverter
}

func TestJet(t *testing.T) {
  var users = []struct {
    Uid int64
  }{}
  err := db.Query(`select * from users where uid > 5894;`).Rows(&users)
  if err != nil {
    log.Fatal(err)
  }
  for _, user := range users {
    log.Printf("User %d", user.Uid)
  }
  query := `update users set name = ? where uid = ?`
  // Note - this hangs
  err = db.Query(query, "test123", 5898).Run()
  if err != nil {
    log.Fatal(err)
  }
  log.Print("All Done")
}

/*
Output
Running [/home/tcolar/apps/go/bin/gofmt, -w, drupsway_test.go]
Running: [go, test] in /home/tcolar/DEV/go/src/bitbucket.org/rivetandsway/drupsway
2014/01/04 11:18:51 query.go:34: >q select \* from users where uid > 5894;
2014/01/04 11:18:51 query.go:36: Lock set
2014/01/04 11:18:51 query.go:123: For
2014/01/04 11:18:51 query.go:133: Scan
2014/01/04 11:18:51 query.go:38: Unlock
2014/01/04 11:18:51 query.go:40: <q select * from users where uid > 5894;
2014/01/04 11:18:51 drupsway_test.go:37: User 5895
2014/01/04 11:18:51 drupsway_test.go:37: User 5897
2014/01/04 11:18:51 drupsway_test.go:37: User 5898

2014/01/04 11:18:51 query.go:34: >q update users set name = ? where uid = ?
2014/01/04 11:18:51 query.go:36: Lock set
2014/01/04 11:18:51 query.go:123: For
... hangs
*/

**Comment by eaigner** [comment]
I think I remember that problem, couldn't find the issue though. If I recall it correctly it's a problem with the MySQL driver.

**Comment by eaigner** [comment]
I think the fix is to use `Exec` instead of `Query` when no arguments are provided. The MySQL driver seems to require this (which is odd).

**Comment by eaigner** [comment]
This line: https://github.com/eaigner/jet/blob/master/query.go#L82

**Comment by tcolar** [comment]
Actually I think I remember similar problem with mysql and the java drivers
as well (way long time ago).

**Comment by tcolar** [comment]
Also the test timed out so I got a trace if that helps

SIGQUIT: quit
PC=0x427929

runtime.epollwait(0x7fff00000004, 0x7fffbbb5dc50, 0xffffffff00000080)
/usr/local/go/src/pkg/runtime/sys_linux_amd64.s:385 +0x19
runtime.netpoll(0xd93701)
/usr/local/go/src/pkg/runtime/netpoll_epoll.c:71 +0x7d
findrunnable()
/usr/local/go/src/pkg/runtime/proc.c:1222 +0x386
schedule()
/usr/local/go/src/pkg/runtime/proc.c:1320 +0xe3
park0(0xc2100697e0)
/usr/local/go/src/pkg/runtime/proc.c:1361 +0xd8
runtime.mcall(0x42553d)
/usr/local/go/src/pkg/runtime/asm_amd64.s:178 +0x4b

goroutine 1 [chan receive]:
testing.RunTests(0x988810, 0xd84220, 0x1, 0x1, 0xeca5a5501)
/usr/local/go/src/pkg/testing/testing.go:472 +0x8d5
testing.Main(0x988810, 0xd84220, 0x1, 0x1, 0xd91120, ...)
/usr/local/go/src/pkg/testing/testing.go:403 +0x84
main.main()
bitbucket.org/rivetandsway/drupsway/_test/_testmain.go:47 +0x9c

goroutine 3 [chan receive]:
database/sql.(*DB).connectionOpener(0xc210053480)
/usr/local/go/src/pkg/database/sql/sql.go:574 +0x3e
created by database/sql.Open
/usr/local/go/src/pkg/database/sql/sql.go:436 +0x24d

goroutine 4 [syscall]:
runtime.goexit()
/usr/local/go/src/pkg/runtime/proc.c:1394

goroutine 5 [IO wait]:
net.runtime_pollWait(0x7f13fe7a88d0, 0x72, 0x0)
/usr/local/go/src/pkg/runtime/netpoll.goc:116 +0x6a
net.(_pollDesc).Wait(0xc2100caae0, 0x72, 0x7f13fe7a72e8, 0xb)
/usr/local/go/src/pkg/net/fd_poll_runtime.go:81 +0x34
net.(_pollDesc).WaitRead(0xc2100caae0, 0xb, 0x7f13fe7a72e8)
/usr/local/go/src/pkg/net/fd_poll_runtime.go:86 +0x30
net.(_netFD).Read(0xc2100caa80, 0xc21007f000, 0x1000, 0x1000, 0x0, ...)
/usr/local/go/src/pkg/net/fd_unix.go:204 +0x2a0
net.(_conn).Read(0xc2100503f8, 0xc21007f000, 0x1000, 0x1000, 0x34, ...)
/usr/local/go/src/pkg/net/net.go:122 +0xc5
github.com/go-sql-driver/mysql.(_buffer).fill(0xc210061c00, 0x4, 0x0, 0x0)
/home/tcolar/DEV/go/src/github.com/go-sql-driver/mysql/buffer.go:46 +0x13a
github.com/go-sql-driver/mysql.(_buffer).readNext(0xc210061c00, 0x4, 0x0,
0x0, 0x0, ...)
/home/tcolar/DEV/go/src/github.com/go-sql-driver/mysql/buffer.go:81 +0x6c
github.com/go-sql-driver/mysql.(_mysqlConn).readPacket(0xc2100ca3f0, 0x0,
0x0, 0x0, 0x0, ...)
/home/tcolar/DEV/go/src/github.com/go-sql-driver/mysql/packets.go:29 +0x7b
github.com/go-sql-driver/mysql.(_mysqlRows).readBinaryRow(0xc210081450,
0xd9c650, 0x0, 0x0, 0x0, ...)
/home/tcolar/DEV/go/src/github.com/go-sql-driver/mysql/packets.go:863 +0x50
github.com/go-sql-driver/mysql.(_mysqlRows).Next(0xc210081450, 0xd9c650,
0x0, 0x0, 0x0, ...)
/home/tcolar/DEV/go/src/github.com/go-sql-driver/mysql/rows.go:68 +0x122
database/sql.(_Rows).Next(0xc210051f00, 0x3)
/usr/local/go/src/pkg/database/sql/sql.go:1509 +0xb8
github.com/eaigner/jet.(_jetQuery).Rows(0xc210051e40, 0x0, 0x0, 0x0, 0x0)
/home/tcolar/DEV/go/src/github.com/eaigner/jet/query.go:125 +0x8d2
github.com/eaigner/jet.(_jetQuery).Run(0xc210051e40, 0x0, 0x0)
/home/tcolar/DEV/go/src/github.com/eaigner/jet/query.go:30 +0x45
bitbucket.org/rivetandsway/drupsway.TestJet(0xc21004d1b0)
/home/tcolar/DEV/go/src/
bitbucket.org/rivetandsway/drupsway/drupsway_test.go:40 +0x39b
testing.tRunner(0xc21004d1b0, 0xd84220)
/usr/local/go/src/pkg/testing/testing.go:391 +0x8b
created by testing.RunTests
/usr/local/go/src/pkg/testing/testing.go:471 +0x8b2

rax     0xfffffffffffffffc
rbx     0xd93760
rcx     0xffffffffffffffff
rdx     0x80
rdi     0x4
rsi     0x7fffbbb5dc50
rbp     0x0
rsp     0x7fffbbb5dc10
r8      0x0
r9      0x0
r10     0xffffffff
r11     0x202
r12     0x752e80
r13     0x98badcfe
r14     0x10325476
r15     0xc3d2e1f0
rip     0x427929
rflags  0x202
cs      0x33
fs      0x0
gs      0x0
**\* Test killed with quit: ran too long (10m0s).
FAIL bitbucket.org/rivetandsway/drupsway 600.036s

**Comment by tcolar** [comment]
So i'm thinking maybe the Run() method should not use Rows(nil) at all but instead has own code that calls query.Exec() and no column mapping & row iteration needed.

Makes sense ?

**Comment by eaigner** [comment]
No, the `Run()` method should invoke rows, because they have common code affecting the LRU.

What needs to be done at [line 82](https://github.com/eaigner/jet/blob/master/query.go#L82), is to check `len(args)` and do a `stmt.Exec` instead with a premature return.

**Comment by tcolar** [comment]
Let me know if you want me to take a stab at implementing that or if you rather do it differently / yourself.

Thanks.

**Comment by eaigner** [comment]
You can try inserting this snipped before line 82

```
if len(args) == 0 {
  _, err := stmt.Exec()
  return err
}
```

**Comment by tcolar** [comment]
Right, I see what you mean, but if calling Exec then no need to do any mapping and all that (Exec does not return rows but a result anyway)

**Comment by tcolar** [comment]
Yeah sounds good, will try that, that should work

**Comment by tcolar** [comment]
That didn't work since I do pass args, just not expecting results.

This worked:
  if v == nil {
    _, err := stmt.Exec()
    return err
  }

Note that likely sooner or later someone will ask to get that Exec result back (cause last_insert_id can be nice to have) but I guess that's another story.

LMK if you want a pull request for that or not.

**Comment by eaigner** [comment]
Yes, my mistake. `v` is what I meant, not `args`.

**Comment by eaigner** [comment]
Pull requests always welcome :)
