### ISSUE TITLE
Multiple Result Sets

### ISSUE THREAD

**Issue by leebrooks0** [eaigner/jet#27]
Does Jet have support for returning multiple result sets?
E.g in one query `select * from x; select * from y`, and then you iterate through the results. This would be useful for eager loading.

**Comment by eaigner** [comment]
That's not a jet issue. The `database/sql` package does not allow multiple statements in one query. That said, what is your example trying to do that a `JOIN` can't accomplish?

You can do `JOIN`s with Jet.

**Comment by leebrooks0** [comment]
I know, but then I get a Cartesian product if I remember the correct word.

If I have a scenario like below where a User has many Addresses, modelled as a struct, how would I then auto populate them with a query via a join? Or with some manual intervention for that matter.

``` go
type User Struct{
     ID int
     Name string
     Addresses []Address
}

type Address Struct{
     ID int
     UserID int
     AddressLine1 string
     AddressLine2 string

}
```

**Comment by eaigner** [comment]
With something like that

```
var rows []struct {
  UserId int
  UserName string
  AddressId int
  AddressLine1 string
  AddressLine2 string
}
db.Query(`SELECT (
    user.id AS user_id,
    user.name AS user_name,
    address.id AS address_id,
    address.address_line1 AS address_line1,
    address.address_line2 AS address_line2
  ) FROM user, address WHERE user.id = address.user_id`
).Rows(&rows)
```

**Comment by leebrooks0** [comment]
And then I loop through that struct and unpack it in to my model?

``` go
var user User
for i, row := range rows{
         if i =0 {
             // Create the user
          }

      // Add the addresses to the users
} 
```

**Comment by eaigner** [comment]
Yes

**Comment by eaigner** [comment]
But your example will not work, since the query returns many user ids, not one, except you limit it to a specific user id in the `WHERE` clause

**Comment by leebrooks0** [comment]
Yes, I would need to modify the above to check if the user is already in the slice. Does one have to alias all the columns?

**Comment by eaigner** [comment]
If you set a custom [ColumnConverter](http://godoc.org/github.com/eaigner/jet#ColumnConverter) on your [Db](http://godoc.org/github.com/eaigner/jet#Db), you can do a custom mapping.

Otherwise no.

**Comment by eaigner** [comment]
But the ColumnConverter is global for the jet instance, so I'd not recommend it.

**Comment by leebrooks0** [comment]
OK, I don't quite get you, by default Jet maps from snake_case to CamelCase and I don't need to do any column aliasing if my schema matches my struct, and otherwise I can just alias my columns in my queries. Is that correct?

**Comment by eaigner** [comment]
Yes

**Comment by leebrooks0** [comment]
OK thanks!
