### ISSUE TITLE
Question : Importing PG driver

### ISSUE THREAD

**Issue by leebrooks0** [eaigner/jet#28]
Is this not necessary when working with Postgres

``` go
import "github.com/lib/pq"
```

This code below works: what driver is being used?

``` go
package db

import (
    "fmt"

    "github.com/eaigner/jet"
    //_ "github.com/lib/pq"
)
func OpenPg() *jet.Db {
    db, err := jet.Open("postgres", "dbname=mobifit_dev user=postgres password=password host=localhost sslmode=disable")

    if err != nil {
        panic(err)
    }

    if err := db.Ping(); err != nil {
        panic(err)
    }

    db.LogFunc = func(queryId, query string, args ...interface{}) {
        fmt.Printf("JET: %s ARG: %v\n", query, args)
    }

    return db
}

// Elsewhere
db := OpenPg()
    var amount int
    db.Query("SELECT 2").Rows(&amount)
    fmt.Println(amount) // = 2
```

**Comment by eaigner** [comment]
Don't know why this works. Do you use this in a test?

The only place where `lib/pq` is imported is in the postgres tests file, so if you use it when running a test case `lib/pq` is imported.

**Comment by leebrooks0** [comment]
No, I have a root/db/jet.go file which creates a *jet.db. I have
recompiled, and deleted the binary which gets run, so this is quite
strange. Either way, good to know I need to import the driver.Thanks

**Comment by leebrooks0** [comment]
I think I have solved this problem, I was using the driver elsewhere in my models for its NullTime type. Importing it elsewhere would have registered the driver correct?

**Comment by eaigner** [comment]
Yes
