### ISSUE TITLE
support for time.Time unmapping

### ISSUE THREAD

**Issue by mattetti** [eaigner/jet#5]
I tried to look at Hood and how I could add this feature but I got stuck in `mapper.go` land.

I'm not quite sure how to unmap a timestamp value coming from MySql into a `time.Time` value. This MySql driver seems to be doing the conversion for you (optionally) https://github.com/go-sql-driver/mysql#timetime-support  but I didn't manage a way to get the unmapping to work if the data comes as a byte array or another type.

As far as I can tell, the challenge is that `unpackStruct` tries to handle the timestamp value and we end up with a blank time value,

``` go
func (m *mapper) unpackStruct(keys []string, values []interface{}, out reflect.Value) error
```

I really wish I could help, but I'm stuck :(

**Comment by eaigner** [comment]
You don't need to touch `unpackStruct` for this. The `unpack` methods are not relevant for that, since they only unpack to the first level of the target struct/map/etc.. The only relevant part for value conversion is

```
func setValue(from, to reflect.Value)
```

If you want to add new type conversions, that's the way to go.

**Comment by eaigner** [comment]
`setValue` takes the `reflect.Value` returned by the driver - `from` - and the target value of the e.g. struct field `to`. So you need to detect what you want to do for a specific `from`/`to` set and implement the conversion there.

**Comment by mattetti** [comment]
I tried to look there, but I checked on the to by using `fmt.Println(to.Type().Name())` I was only getting simple types like: 

```
bool
string
int
```

But no signs of `Time`. So or I'm not using reflection properly (which wouldn't be surprising) or `unpackStruct` breaks down `time.Time` or whatever and I can't find the right entry point.

**Comment by eaigner** [comment]
So did the latest commit fix your issue?

But I guess not, since it converts `time.Time` to `int64`, and your problem was that the MySQL driver didn't give you a `time.Time` object. So it's basically the other way round :).

**Comment by eaigner** [comment]
I guess that fix was what you're looking for? https://github.com/eaigner/jet/commit/db1586e70f85de1edc1a090ff653784baa9cfb97

**Comment by mattetti** [comment]
That's what I was looking for, testing today. I noticed your commit just
before going to bed.

**Comment by mattetti** [comment]
Unfortunately the latest commits seem to break something with MySQL:

```
--- FAIL: TestCreateProject (0.00 seconds)
panic: reflect.Value.Convert: value of type []uint8 cannot be converted to type time.Time [recovered]
    panic: reflect.Value.Convert: value of type []uint8 cannot be converted to type time.Time

goroutine 11 [running]:
testing.func·004()
    /usr/local/Cellar/go/1.1.1/src/pkg/testing/testing.go:348 +0xcd
reflect.Value.Convert(0x22c120, 0xc2004bfe80, 0x172, 0xc2000ba000, 0x2f9000, ...)
    /usr/local/Cellar/go/1.1.1/src/pkg/reflect/value.go:2143 +0x1ad
github.com/eaigner/jet.convertAndSet(0x22c120, 0xc2004bfe80, 0x2f9000, 0xc20010c968, 0x196, ...)
    /Users/mattetti/Code/golang/src/github.com/eaigner/jet/mapper.go:105 +0xbd
github.com/eaigner/jet.setValueFromBytes(0xc2004bfd20, 0x13, 0x13, 0x2f9000, 0xc20010c968, ...)
    /Users/mattetti/Code/golang/src/github.com/eaigner/jet/mapper.go:142 +0x371
github.com/eaigner/jet.setValue(0x2361e0, 0xc2004808e0, 0x146, 0x2f9000, 0xc20010c968, ...)
    /Users/mattetti/Code/golang/src/github.com/eaigner/jet/mapper.go:114 +0xfd
github.com/eaigner/jet.(*mapper).unpackSimple(0xc2004808a0, 0x0, 0x0, 0x0, 0xc200392e70, ...)
    /Users/mattetti/Code/golang/src/github.com/eaigner/jet/mapper.go:98 +0x14f
github.com/eaigner/jet.(*mapper).unpackStruct(0xc2004808a0, 0x0, 0x0, 0x0, 0xc200392e70, ...)
    /Users/mattetti/Code/golang/src/github.com/eaigner/jet/mapper.go:61 +0xa3
github.com/eaigner/jet.(*mapper).unpackValue(0xc2004808a0, 0x0, 0x0, 0x0, 0xc200392e70, ...)
    /Users/mattetti/Code/golang/src/github.com/eaigner/jet/mapper.go:37 +0x42b
github.com/eaigner/jet.(*mapper).unpackStruct(0xc2004808a0, 0xc200392c00, 0xc, 0xc, 0xc200392e40, ...)
    /Users/mattetti/Code/golang/src/github.com/eaigner/jet/mapper.go:72 +0x2c3
github.com/eaigner/jet.(*mapper).unpackValue(0xc2004808a0, 0xc200392c00, 0xc, 0xc, 0xc200392e40, ...)
    /Users/mattetti/Code/golang/src/github.com/eaigner/jet/mapper.go:37 +0x42b
github.com/eaigner/jet.(*mapper).unpackValue(0xc2004808a0, 0xc200392c00, 0xc, 0xc, 0xc200392e40, ...)
    /Users/mattetti/Code/golang/src/github.com/eaigner/jet/mapper.go:29 +0x2bf
github.com/eaigner/jet.(*mapper).unpack(0xc2004808a0, 0xc200392c00, 0xc, 0xc, 0xc200392e40, ...)
    /Users/mattetti/Code/golang/src/github.com/eaigner/jet/mapper.go:20 +0x200
github.com/eaigner/jet.(*runner).Rows(0xc20009ff00, 0x2e2780, 0xc20010c8f0, 0x0, 0x0, ...)
    /Users/mattetti/Code/golang/src/github.com/eaigner/jet/runner.go:130 +0x591
```

Not quite sure what's going on yet.

**Comment by mattetti** [comment]
from what I can see, the issue is that the mysql driver returns the time value in a different format than postgres.
Thoughts?

**Comment by eaigner** [comment]
The difference is that the MySQL driver returns everything as a string, and the Postgres driver returns correct types for each column.

**Comment by mattetti** [comment]
are you suggesting that the driver should be fixed or that jet should
handle that painful fact?

**Comment by eaigner** [comment]
I don't know if it's even fixable in the driver, because I don't know if you can infer the column types from the SQL protocol. Jet could handle it of course, but someone would need to be willing to invest a few hours in completely implementing/testing MySQL support  :)

**Comment by eaigner** [comment]
I guess the easiest thing would be if you just post example code that is making problems, so I can add a test case for that.

**Comment by mattetti** [comment]
Certainly, I'll come up with examples for the main data types.

**Comment by mattetti** [comment]
Here you go:
https://gist.github.com/mattetti/6152121

I also added how I manually parse a MySQL string value into a time object.
Also, note that the driver has an option to autoparse date object, but it didn't make a difference, probably due to the way jet parses the incoming data.

``` go
    dataSource := fmt.Sprintf("%s:%s@tcp(%s:%d)/%s?charset=utf8&parseTime=true", username, password, host, port, dbName)
```

**Comment by mattetti** [comment]
@eaigner please let me know if there is example worked for you or if you need anything else.

**Comment by mattetti** [comment]
I tried to update to the latest rev on master and I really enjoy some of the cleanups like `LogFunc` but I had to revert since time isn't supported on MySql (still getting `panic: reflect.Value.Convert: value of type []uint8 cannot be converted to type time.Time`).  

Is there anything I can do to help you fix that, or can you give me pointers to look at it myself?

Thanks

**Comment by mattetti** [comment]
For my own sake:

https://github.com/eaigner/jet/blob/master/mapper.go#L91
calls:
`setValue(reflect.Indirect(reflect.ValueOf(values[0])), out)`

https://github.com/eaigner/jet/blob/master/mapper.go#L114
`setValueFromBytes(t, to)`

https://github.com/eaigner/jet/blob/master/mapper.go#L142
`convertAndSet(t, to)`

https://github.com/eaigner/jet/blob/master/mapper.go#L105
`to.Set(from.Convert(to.Type()))`

So the tricky part looks like we need to check the expected type and do some custom parsing to get to the value we expect. 

The MySql time layout is `"2006-01-02 15:04:05"`

**Comment by eaigner** [comment]
In order to avoid handling this with a special case for every driver, jet now supports a [ComplexValue](http://godoc.org/github.com/eaigner/jet#ComplexValue) type to support en/decoding of custom values to a format the DB understands.

**Comment by mattetti** [comment]
would you mind showing me a quick examples on how to use ComplexValue to handle time types please?
