### ISSUE TITLE
weird error probably due to caching

### ISSUE THREAD

**Issue by mattetti** [eaigner/jet#7]
I see seldom errors like this one:

```
sql: expected 12 arguments, got 1
```

When logging the query that triggered the error, I can see that the query is actually the wrong one:

```
Query: &jet.runner{db:(*sql.DB)(0xc2000d02a0), tx:(*sql.Tx)(nil), stmt:(*sql.Stmt)(0xc20165d600), qo:(*sql.DB)(0xc2000d02a0), conv:(*jet.snakeConv)(0x8e0a88), expand:false, txnId:"", query:"select * from users WHERE authentication_token = ? limit 1", lastErr:error(nil), args:[]interface {}{"XXXXXX"}, logger:(*jet.Logger)(nil), lru:(*jet.lruCache)(0xc2000c1820)}
```

So for some reason, Jet gets confused and uses the wrong statement which then fails since the passed arguments don't match.

Any idea what's going on?

**Comment by mattetti** [comment]
Note that the logger reports the right query.

**Comment by mattetti** [comment]
@eaigner is there a way to disable the lru cache? I'm not sure that's the problem but I'm sure the wrong query is being executed so anything I can do to fix this issue would help

**Comment by eaigner** [comment]
There's currently no way to disable the LRU with a flag. Just fork it and remove it.

**Comment by eaigner** [comment]
LRU is now settable https://github.com/eaigner/jet/commit/f49825cb888711dbebdcf46d6af949de2ebb70dd

**Comment by mattetti** [comment]
Thanks @eaigner I've also updated the mysql driver to the latest version git master and I'll run more tests to try the root cause of the bug I see.

**Comment by eaigner** [comment]
Beware. I've changed some stuff in the recent release, so merging won't be trivial.

**Comment by mattetti** [comment]
ok, I'll reset my branch. Last I looked master was broken for me due to the new time parser and mysql tho.
