### ISSUE TITLE
Expose LastInsertId()/RowsAffected()

### ISSUE THREAD

**Issue by simonklee** [eaigner/jet#8]
As far as I can see there is no way of getting this from a result. I see in your tests you use some PostgreSQL specific queries to work around the issue.

**Comment by eaigner** [comment]
Thats true, there is no way to get the SQL result right now, mainly because I designed it using Postgres. But I wouldn't introduce new methods for this, wen It can be returned by existing methods (`Run`, `Rows`).

**Comment by simonklee** [comment]
Yep, that is a better design. I created the pull request just to show that it was missing. Didn't expect you to make the Runnable Interface more complicated as it's quite nice as it is :)
